source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SolidPod_Example', :exclusive => true do
  pod "SolidPod", :path => "../"
end

target 'SolidPod_Tests', :exclusive => true do
  pod "SolidPod", :path => "../"

  
end
